@echo off
echo Starting CARLA...
start /B "" "%CARLA_PATH%\CarlaUE4.exe"
timeout /t 20 /nobreak > NUL
echo Waiting for CARLA to initialize...
echo Starting manual control script...
call "%ANACONDA_SCRIPTS_PATH%\activate.bat" carla-env
"%PYTHON_CARLA%" "%CARLA_MANUAL_CONTROL%"
echo Script has ended. Closing...
timeout /t 10
