@echo off
echo Starting CARLA...
start /B "" "%CARLA_PATH%\CarlaUE4.exe"
timeout /t 20 /nobreak > NUL
echo Waiting for CARLA to initialize...
echo Starting manual control script...
"C:\Users\saaso\anaconda3\envs\carla-env\python.exe" "%CARLA_MANUAL_CONTROL%"
echo Script has ended. Closing...
timeout /t 10
